export interface GeneratorColumn {
  id: string;
  header: string;
}

export const GENERATOR_COLUMNS: GeneratorColumn[] = [
  { id: 'wer', header: 'WER ODER WAS?' },
  { id: 'charakter', header: 'WIE? (Charakter)' },
  { id: 'verb', header: 'VERB' },
  { id: 'modus', header: 'WIE? (Modus)' },
  { id: 'situation', header: 'SITUATION/KONFLIKT' },
  { id: 'kontext', header: 'KONTEXT' },
];

export const GENERATOR_ROW_1: Record<string, string[]> = {
  wer: [
    'Der Protagonist/die Protagonistin',
    'Die Figur',
    'Das lyrische Ich',
    'Das lyrische Du',
    'Die Ich-Erzählerin',
    'Der autodiegetische Erzähler',
    '…',
  ],
  charakter: [
    'passiv',
    'phlegmatisch',
    'leidenschaftliche',
    'aggressive',
    'frustrierte',
    'grüblerische',
    'desillusionierte',
    'unbekümmerte',
    'sensible',
    'dünnhäutige',
    'von (z. B.) Neid getriebene',
    'lebensfremde',
    'vereinsamte',
    '…',
  ],
  verb: [
    'kämpft für/gegen',
    'kritisiert',
    'hadert mit',
    'fühlt sich',
    'agiert',
    'wird aktiv',
    'spricht an',
    'gestaltet',
    'muss erkennen',
    'durchschaut',
    'entdeckt',
    'beschreibt',
    'fürchtet',
    'zerbricht an',
    'reflektiert',
    'durchlebt',
    'erschafft',
    'entfernt sich von',
    'beklagt',
    '…',
  ],
  modus: [
    'auf humorvolle Weise',
    'mit sarkastischem Unterton',
    'schwärmerisch',
    'sehnsüchtig',
    'auf zwiespältige Weise',
    'mit letzter Kraft',
    'satirisch',
    'entlarvend',
    '(betont) unterkühlt',
    'leidenschaftlich',
    'demütig',
    'mühevoll',
    'träumerisch',
    'emphatisch',
    'bildhaft und wortreich',
    '…',
  ],
  situation: [
    'ihre/seine Rolle als…',
    'das gesellschaftliche Konstrukt des …',
    'mit sich selbst / seinem Selbstbild',
    'den eigenen Idealen und Wertvorstellungen',
    'offenkundige Kommunikationsschwierigkeiten',
    'die Unmenschlichkeit/Unmöglichkeit des/der…',
    'seine/ihre eigene utopische Fantasiewelt',
    'den Konflikt/Kontrast zwischen…',
    'die Ambivalenz der/des…',
    'den Widerspruch von…',
    '…',
  ],
  kontext: [
    'am Beispiel des…',
    'vor dem Hintergrund des/der…',
    'in einer postmodernen Welt',
    'im Nachkriegsdeutschland der Fünfzigerjahre',
    'in Anlehnung an den aufklärerischen Toleranzgedanken',
    'als Appell für/gegen…',
    'Anonymität der Großstadt',
    'Auflösung der Familienstrukturen',
    '… (werkimmanent oder mit textexternem Bezug)',
  ],
};

export const GENERATOR_ROW_2: Record<string, string[]> = {
  wer: ['Der Roman', 'Das Drama', 'Das Gedicht', 'Die Kurzgeschichte', 'Das Lied', '…'],
  verb: ['zeigt auf…', 'kritisiert…', 'verweist auf…', 'stellt dar…', 'spielt auf…an', 'greift auf…', 'thematisiert'],
};
